### ISSUE TITLE
Bug: 任务管理器的搜索框中无法正常切换

### ISSUE THREAD

**Issue by he0119** [mbbill/no_english_mode#1]
https://github.com/mbbill/no_english_mode/assets/5219550/4d9b2eb5-6fbc-4fc8-9292-a789aacd233a

直接从 2728a62b11e20540e3e163c428974b9c3dfc803e 编译的版本。不过如果通过设置的 ctrl+space 键则可以正常切换。

系统信息：
版本	Windows 11 专业版
版本	23H2
安装日期	‎2023/‎7/‎30
操作系统版本	22631.2861
体验	Windows Feature Experience Pack 1000.22681.1000.0

**Comment by mbbill** [comment]
能不能描述的详细一点？看不太懂哪里是bug，无法正常切换是指在任务管理器里面切换输入法吗？

**Comment by he0119** [comment]
> 能不能描述的详细一点？看不太懂哪里是bug，无法正常切换是指在任务管理器里面切换输入法吗？

是的，我发现输入法在任务管理器那个搜索框中无法自动切换。其实视频能看出来吧，切换到任务管理器之后，输入法是英文的，但是切换到其他地方就是中文了。

**Comment by mbbill** [comment]
我猜有可能是因为任务管理器是高权限窗口，你用管理员模式运行一下这个软件试试

**Comment by he0119** [comment]
> 我猜有可能是因为任务管理器是高权限窗口，你用管理员模式运行一下这个软件试试

真可以了，好耶。居然是这个原因。
