### ISSUE TITLE
24H2 貌似已经失效？

### ISSUE THREAD

**Issue by PhilDavisAB** [mbbill/no_english_mode#4]
我前段时间升级到了24H2，不过在24H2之前也并没有用过这个小工具。只不过我现在使用下来微信、QQ等软件依然会自动切换为英文，貌似已经失效？是否有其他人有同样的问题或者作者是否能够排查一下呢？

**Comment by mbbill** [comment]
等正式版发布了再看看吧

**Comment by YYY0ung** [comment]
+1 
现在微信 浏览器都会偶尔出现英文输入

**Comment by mbbill** [comment]
试试看这个 https://github.com/mbbill/no_english_mode/releases/tag/1.1

**Comment by YYY0ung** [comment]
在chatgpt输入的时候还是有概率变成英文 但是问题不能准确复现

**Comment by Az-CMQ** [comment]
我这边是好使的
![image](https://github.com/user-attachments/assets/a12238ef-2401-4419-937f-68d7d99ee294)
