### ISSUE TITLE
使用visual studio2022时选中编译栏无法自动切换成中文

### ISSUE THREAD

**Issue by Shacia** [mbbill/no_english_mode#5]
希望能解决问题，谢谢，这个项目很好用

**Comment by mbbill** [comment]
选中编译栏是指？
这个app只会在输入框获得focus的时候切换中文。其他地方不会有效果，毕竟我理解选中编译栏的时候切换成中文并没有什么实际作用吧。

**Comment by Shacia** [comment]
就是写代码的地方，刚开始学有的地方要用//中文写注释，偶尔会出现无法自动转换成中文的情况，写英文内容习惯用win+空格切换到英语输入

**Comment by mbbill** [comment]
这可能没有办法。win+空格切换到中文输入法的时候也是不会触发focus事件的，所以如果中文输入法默认是在英文模式，那就会保持英文。没有太好的办法，可以试试用shift切换

**Comment by Shacia** [comment]
好吧，还是谢谢你
